-- Create Trainings Table
create table public.trainings (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  media_url text, -- YouTube link or storage URL
  image_url text, -- Thumbnail URL
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

-- RLS Policies
alter table public.trainings enable row level security;

-- Everyone can read active trainings
create policy "Everyone can read active trainings"
on public.trainings for select
using (is_active = true);

-- Admins can do everything (assuming admin check is done via app or service role, 
-- but traditionally for simple apps we might just allow authenticated write if we had robust role checks. 
-- For now, let's allow all authenticated users to INSERT/UPDATE if they are admins, 
-- or simply rely on the Admin Panel using the Service Key or having a specific role check).

-- Since we don't have a robust 'admin' role check function in SQL yet widely used, 
-- we will assume the Admin Panel uses a Supabase user with a specific role claim or simply we allow authenticated users to *read* everywhere,
-- and only specific users to write. 
-- For simplicity in this project context (where Admin Panel is separate), we often keep it open or rely on implicit trust for 'authenticated' if not strictly public.
-- BUT, to be safe, let's restrict write to service_role or specific admin check if possible.
-- Given previous schema, profiles has a 'role' column.

create policy "Admins can insert trainings"
on public.trainings for insert
with check (
  exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  )
);

create policy "Admins can update trainings"
on public.trainings for update
using (
  exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  )
);

create policy "Admins can delete trainings"
on public.trainings for delete
using (
  exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  )
);
