-- TC Referans tablosunu yeniden oluştur (duplicate'lara izin vererek)
-- Bu sayede bulk import çok daha hızlı olacak

DROP TABLE IF EXISTS public.tc_referans;

CREATE TABLE public.tc_referans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tc_kimlik TEXT NOT NULL,
  referans_kodu TEXT NOT NULL
);

-- TC araması için index
CREATE INDEX idx_tc_referans_tc_kimlik ON public.tc_referans(tc_kimlik);

-- RLS kapalı (bulk import için)
-- ALTER TABLE public.tc_referans ENABLE ROW LEVEL SECURITY;
