-- 1. PROFİLLER (Üyeler)
create table public.profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  city text,
  district text,
  neighborhood text,
  topics text[], -- Örn: ['Ekonomi', 'Gençlik']
  role text default 'member', -- 'member', 'admin', 'district_head'
  points int default 0,
  avatar_url text,
  created_at timestamp with time zone default now()
);

-- 2. İÇERİK PAKETLERİ (Genel Merkezden gelen haftalık setler)
create table public.content_packs (
  id bigint generated by default as identity primary key,
  week_number int,
  topic text, -- 'Ekonomi'
  title text,
  message_framework text, -- Sahada söylenecek 3 cümle
  survey_questions jsonb, -- Saha soruları: [{q: "Soru 1?", type: "text"}]
  media_url text, -- PDF veya Video linki
  start_date date, -- Görevin başlayacağı tarih
  end_date date, -- Görevin biteceği tarih
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

-- 3. GÖREVLER (Üyelere atanan işler)
create table public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  content_pack_id bigint references public.content_packs(id),
  status text default 'pending', -- 'pending', 'completed'
  assigned_at timestamp with time zone default now(),
  completed_at timestamp with time zone
);

-- 4. SAHA RAPORLARI (Geri Bildirimler)
create table public.reports (
  id bigint generated by default as identity primary key,
  task_id bigint references public.tasks(id),
  user_id uuid references public.profiles(id),
  contact_type text, -- 'Esnaf', 'Komşu', 'Genç', 'Akraba'
  reaction text, -- 'Olumlu', 'Nötr', 'Olumsuz'
  feedback_note text,
  location_lat float,
  location_lng float,
  created_at timestamp with time zone default now()
);
